emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/openapi3"
options:
  "@azure-tools/typespec-autorest":
    output-file: "{emitter-output-dir}/{service-name}/{version}/openapi.json"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
