baseBranch: main

changeKinds:
  internal:
    versionType: none
    title: Internal
    description: Internal changes that are not user facing

  fix:
    versionType: patch
    title: Bug Fix
    description: Fixes to existing features

  dependencies:
    versionType: patch
    title: Bump dependencies
    description: Bumps dependencies

  feature:
    versionType: minor
    title: Feature
    description: Adds new features

  deprecation:
    versionType: minor
    title: Deprecation
    description: Change that deprecate an existing feature but is not breaking.

  breaking:
    versionType: major
    title: Breaking Change
    description: Changes that break existing features

versionPolicies:
  - name: typespec-azure
    type: lockstep
    step: minor
    packages:
      - "@azure-tools/typespec-autorest"
      - "@azure-tools/typespec-azure-core"
      - "@azure-tools/typespec-azure-portal-core"
      - "@azure-tools/typespec-azure-resource-manager"
      - "@azure-tools/typespec-client-generator-core"
      - "typespec-azure-vscode"

changelog: ["@chronus/github/changelog", { repo: "azure/typespec-azure" }]

ignore:
  - "@typespec/*"

changedFiles:
  - "!**/*.md"
  - "!**/*.test.ts"
  - "!**/*.e2e.ts"
