emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-autorest-canonical"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    output-file: "{emitter-output-dir}/{version-status}/{version}/widget.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-tools/typespec-autorest-canonical":
    emitter-output-dir: "{project-root}/.."
    output-file: "{emitter-output-dir}/canonical/openapi.json"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
