parameters:  
  "service-dir":
    default: "sdk/azure-core_stand_alone"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":    
    package-dir: "azure-contoso"
    namespace: "azure.contoso"
    package-mode: dataplane
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Contoso"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
  "@azure-tools/typespec-ts":
    package-dir: "azure-contoso-rest"
    is-modular-library: false
    package-details:
      name: "@azure-rest/azure-contoso"
      description: "Azure.Contoso Service"
    flavor: azure
  "@azure-tools/typespec-java":
    package-dir: "azure-contoso"
    namespace: com.azure.contoso
